### ISSUE TITLE
Amp tag not being set on index.html

### ISSUE THREAD

**Issue by iamtylerd** [jafaircl/gatsby-plugin-amp#11]
Setup below
`config`
```{
      resolve: 'gatsby-plugin-amp',
      options: {
        analytics: {
          type: 'gtag',
          dataCredentials: 'include',
          config: {
            vars: {
              gtag_id: '{{tag}}',
              config: {
                '{{tag}}': {
                  page_location: '{{pathname}}',
                },
              },
            },
          },
        },
        canonicalBaseUrl: 'https://domain.com/',
        components: ['amp-form'],
        excludedPaths: ['/404*', '/'],
        pathIdentifier: '/amp/',
        relAmpHtmlPattern: '{{canonicalBaseUrl}}{{pathname}}{{pathIdentifier}}',
        useAmpClientIdApi: true,
      },
```

`node`

```
createPage({
  path: `${result.data.wordpressPost.slug}/amp`,
  component: slash(ampPostTemplate),
  context: {
    id: result.data.wordpressPost.id,
  },
});
```

My `ampPostTemplate` is a condensed version of my original template.  When I view the /amp/index.html I do not see the `amp` tag in the head and I see js still, but my `react-data-helmet` items are showing up in the index.html (they are in my post template).  Do I need to change anything in my `html.js` file?
```export default class HTML extends React.Component {
  render() {
    return (
      <html  {...this.props.htmlAttributes}>
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
         
          {this.props.headComponents}
        </head>
        <body {...this.props.bodyAttributes}>
          {this.props.preBodyComponents}
          <div
            key="body"
            id="___gatsby"
            dangerouslySetInnerHTML={{ __html: this.props.body }}
            />
          {this.props.postBodyComponents}
        </body>
      </html>
    )
  }
}
```

Also I am on Gatsby 2.0.66
Thanks for the help

**Comment by jafaircl** [comment]
Can you try removing "/" from the exculdedPaths array and see if it works?

**Comment by iamtylerd** [comment]
Thanks for the quick response, didn't seem to fix the issue.  Here is my config options minus GA

```
canonicalBaseUrl: 'https://domain.com/',
components: ['amp-layout'],
excludedPaths: ['/404*'],
relAmpHtmlPattern: '{{canonicalBaseUrl}}{{pathname}}',
useAmpClientIdApi: true,
```

Also changed components to amp-layout seems to be more generic

**Comment by iamtylerd** [comment]
Also here is my layout render func I simplified it just for testing
```
render={() => (
      <div>
       {children}
      </div>
    )}
```

**Comment by jafaircl** [comment]
Could you try adding this:

```javascript
...
includedPaths: [“/*”],
...
```
to the config? I’m thinking I may have considered having an index page as an AMP page an edge case, which may not be true now that you mention it.

**Comment by iamtylerd** [comment]
Sorry if I didnt explain it, basically converting `/post-1` `/post-2` etc.  What i am seeing is its adding the `<link rel="amphtml" href="https://domain.com/test-amp/amp">` which is the opposite of what I want correct?

**Comment by jafaircl** [comment]
Your page at `https://domain.com/test-amp/amp/index.html` should have a `<link rel=“canonical” href=“https://domain.com/test-amp/” />` tag and your page at `https://domain.com/test-amp/index.html` should have a `<link rel=“amphtml” href=“https://domain.com/test-amp/amp” />` tag. Is that what you’re seeing?

**Comment by iamtylerd** [comment]
Currently both have ```link rel=“amphtml”```

```
{
      resolve: 'gatsby-plugin-amp',
      options: {
        analytics: {
          type: 'gtag',
          dataCredentials: 'include',
          config: {
            vars: {
              gtag_id: '',
              config: {
                '': {
                  page_location: '{{pathname}}',
                },
              },
            },
          },
        },
        canonicalBaseUrl: 'https://domain.com/',
        components: ['amp-layout'],
        excludedPaths: ['/404*'],
        includedPaths: ['/*'],
        relAmpHtmlPattern: '{{canonicalBaseUrl}}{{pathname}}',
        useAmpClientIdApi: true,
      },
    },
```
node

```
createPage({
    path: `test-amp/amp`,
    component: path.resolve('./src/templates/test.amp.js'),
    context: {
      slug: 'test-amp',
    },
  })
  createPage({
    path: `test-amp`,
    component: path.resolve('./src/templates/test.js'),
    context: {
      slug: 'test-amp',
    },
  })
```
They both use the same template, just one is `test.amp.js` and other is `test.js`

**Comment by iamtylerd** [comment]
Also when running a `yarn develop gatsby` I am not seeing either canonical or amphtml.  Not sure if that is the intended behavior

**Comment by jafaircl** [comment]
That isn’t the intended behavior. Is there any way you could provide a minimal gatsby template that reproduces your issue? I’d like to see if I can figure out what’s happening and if I can do anything to fix it.

**Comment by iamtylerd** [comment]
Here ya go, hopefully I am just missing something easy. Thanks
https://github.com/iamtylerd/amp-test

**Comment by iamtylerd** [comment]
@jafaircl were you able to reproduce?

**Comment by jafaircl** [comment]
Sorry about that. Yes I was able to reproduce it. The first thing I see is that `pathIdentifier: "/amp/",` dropped out of the options in `gatsby-config.js`. I see that it was in your config in the first version in this issue. So it probably just fell out during debugging. You do need to put it back, though. You don't need the `includedPaths: ['/*'],` after all if you want to take it out.

To fix your issue, you'll need to do one of 2 things:

1. In your `gatsby-config.js`, change `pathIdentifier: "/amp/",` to `pathIdentifier: "/amp",`
2. In your `gatsby-node.js`, make this change:
```javascript
... // line 13
createPage({
    path: `test-amp/amp`, // change this path to `test-amp/amp/`
...
```

Don't do them both or you'll be right back where you started. In my opinion, the second option is the better way to go. Otherwise the plugin will try to make any page that has a url that starts with `/amp...` into an AMP page. That may not ever happen but you may forget about it and start throwing errors with no idea why if it does.

**Comment by iamtylerd** [comment]
@jafaircl Awesome seems so fix most of the issues, I am seeing "canonical" on the amp page and "amphtml" on the non amp page, but the "amphtml" is pointing to itself ("test-page" instead of "test-page/amp/"

I pushed the new changes up

**Comment by jafaircl** [comment]
You need to change your `relAmpHtmlPattern` to be `{{canonicalBaseUrl}}{{pathname}}{{pathIdentifier}}`

**Comment by iamtylerd** [comment]
Awesome thanks for the help!
