### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by c0b41** [jafaircl/gatsby-plugin-amp#6]
[onPreRenderHTML](https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML) and [replaceRenderer](https://www.gatsbyjs.org/docs/ssr-apis/#replaceRenderer) methods dont support `pathname` and never called plugin code blocks

**Comment by jafaircl** [comment]
What version of gatsby are you using?

**Comment by c0b41** [comment]
@jafaircl `2.0.10`

**Comment by jafaircl** [comment]
The commit adding pathname to those APIs was [merged](https://github.com/gatsbyjs/gatsby/pull/9792) on 11/7/18 which would be [version 2.0.41](https://github.com/gatsbyjs/gatsby/commit/f9714a5646523bc728586e3692190507ad68e6c1#diff-d42476695f98af8f85d595ac39bc0653) so you'll need to have at least that version.

**Comment by c0b41** [comment]
@jafaircl thanks :)
